### ISSUE TITLE
it is not compatible with redmine_local_avatar.

### ISSUE THREAD

**Issue by archonwang** [berti92/mega_calendar#25]
ur... could you fix it ,Thanks so much..
the error occured when I migrate db 
los is:

> /opt/redmine/plugins/redmine_issue_checklist/init.rb:24: warning: duplicated key at line 24 ignored: :issue_checklist
> rake aborted!
> uninitialized constant LocalAvatarsPlugin::UsersControllerPatch
> /opt/redmine/plugins/redmine_local_avatars/init.rb:37:in `block in <top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `instance_exec'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `each'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in `run_callbacks'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `instance_exec'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in `block in run_initializers'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:352:in `initialize!'
> /opt/redmine/config/environment.rb:14:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:328:in `require_environment!'
> /usr/local/rvm/gems/ruby-2.2.4@newgemset/gems/railties-4.2.5.2/lib/rails/application.rb:457:in `block in run_tasks_blocks'
> Tasks: TOP => redmine:plugins:migrate => environment
> (See full trace by running task with --trace)

**Comment by berti92** [comment]
Which version of Redmine do you use and which version (with link please) of the plugin redmine_local_avatar do you use?

Thanks.

**Comment by archonwang** [comment]
Environment:

>   Redmine version                3.3.0.stable.15784
>   Ruby version                   2.2.4-p230 (2015-12-16) [x86_64-linux]
>   Rails version                  4.2.7.1
>   Environment                    production
>   Database adapter               Mysql2

**Comment by archonwang** [comment]
Redmine local avatars  V0.2.0
https://github.com/thorin/redmine_local_avatars.git
