### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by yanOnGithub** [berti92/mega_calendar#59]
C:\Bitnami\redmine-3.3.1-0\apps\redmine\htdocs>bundle exec thin start -e production -p 3001 -prefix /redmine
Warning: this Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source. To upgrade this warning to an error, run `bundle config disable_multisource true`.
C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1-x86-mingw32/lib/thin/controllers/controller.rb:37:in `start': wrong number of arguments (1 for 0) (ArgumentError)
        from C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:200:in `run_command'
        from C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1-x86-mingw32/lib/thin/runner.rb:156:in `run!'
        from C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/thin-1.6.1-x86-mingw32/bin/thin:6:in `<top (required)>'
        from C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/bin/thin:23:in `load'
        from C:/Bitnami/redmine-3.3.1-0/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/bin/thin:23:in `<main>'

**Comment by yanOnGithub** [comment]
The instruction here worked. Thx.
https://www.redmineup.com/pages/help/checklists/installing-redmine-checklists-plugin-on-linux
