### ISSUE TITLE
Install failed on Bitnami Redmine 3.3.2

### ISSUE THREAD

**Issue by ilkz** [berti92/mega_calendar#60]
When i try to make "bundle exec rake redmine:plugins:migrate RAILS_ENV=production" from bitnami shell (use_redmine) i get follow errors:

```
root@RedmineLinux:~/redmine/apps/redmine/htdocs# bundle exec rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
LoadError: cannot load such file -- vpim
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/master/redmine/apps/redmine/htdocs/plugins/mega_calendar/init.rb:2:in `<top (required)>'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
/home/master/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:155:in `block in load'
/home/master/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `each'
/home/master/redmine/apps/redmine/htdocs/lib/redmine/plugin.rb:146:in `load'
/home/master/redmine/apps/redmine/htdocs/config/initializers/30-redmine.rb:21:in `<top (required)>'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:652:in `block in load_config_initializer'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:651:in `load_config_initializer'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `each'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/engine.rb:615:in `block in <class:Engine>'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:30:in `run'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `each'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:44:in `tsort_each_child'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/initializable.rb:54:in `run_initializers'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:352:in `initialize!'
/home/master/redmine/apps/redmine/htdocs/config/environment.rb:14:in `<top (required)>'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:328:in `require_environment!'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/railties-4.2.7.1/lib/rails/application.rb:457:in `block in run_tasks_blocks'
/home/master/redmine/apps/redmine/htdocs/vendor/bundle/ruby/2.1.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)
```

I try "gem install vpim", but have no effect.

**Comment by berti92** [comment]
Hi, sorry I can not reproduce your problem (+ I don't use Bitnami).
Maybe the solution from issue #59 helps you:
https://www.redmineup.com/pages/help/checklists/installing-redmine-checklists-plugin-on-linux

**Comment by ilkz** [comment]
Hmmm, Bitnami is so popular framework. Can you test it on it?

**Comment by berti92** [comment]
Thank you for your feedback 👍 
I added the workaround to the [wiki](https://github.com/berti92/mega_calendar/wiki/FAQ).
